
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:{
    absolute:'',
    default:'Next.js App',
    template:'%s | Hayans App'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className="flex flex-col justify-between h-screen items-center 
       ">
       <header className="w-full flex flex-col justify-between items-center text-center" style={{backgroundColor:'lightblue',padding:'1rem'}}>
          
        </header>
        {children}

        <footer className="w-full text-center" style={{backgroundColor:'lightblue',padding:'1rem'}}>
          <p>Footer</p>
        </footer>
       </div>
        
        </body>
    </html>
  );
}
