/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8nDNUcIuMHt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function ClientLandingPage() {
  return (
    (<div className="flex flex-col min-h-screen font-poppins">
      <header
        className="bg-primary text-primary-foreground w-full py-16 px-4 md:px-6 flex items-center justify-center">
        <div className="container mx-auto max-w-5xl text-center">
          <h1 className="text-4xl font-bold md:text-6xl">Bad google review? Not anymore!</h1>
        </div>
      </header>
      <main className="flex-1 bg-background">
        <section className="container mx-auto max-w-5xl py-12 md:py-16">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="col-span-1 md:col-span-2">
              <h2 className="text-2xl font-bold mb-4">How it works</h2>
              <div className="space-y-8">
                <div>
                  <h3 className="text-xl font-semibold mb-2">Step 1: Top up balance</h3>
                  <p className="text-muted-foreground">
                    Add funds to your account to cover the cost of removing the negative review.
                  </p>
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">Step 2: Enter the Google Maps link and description</h3>
                  <p className="text-muted-foreground">
                    Provide the link to the Google Maps page with the negative review and a brief description.
                  </p>
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">
                    Step 3: Place order and wait until the review is deleted
                  </h3>
                  <p className="text-muted-foreground">
                    Once you've placed the order, our team will work to have the negative review removed from Google.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-span-1 bg-muted rounded-lg p-6">
              <h2 className="text-2xl font-bold mb-4">We won't charge you if the review is not deleted</h2>
              <form className="space-y-4">
                <div>
                  <label htmlFor="email" className="block text-sm font-medium mb-1">
                    Email
                  </label>
                  <input
                    type="email"
                    id="email"
                    className="bg-background border border-input rounded-md px-3 py-2 w-full"
                    placeholder="Enter your email" />
                </div>
                <div>
                  <label htmlFor="name" className="block text-sm font-medium mb-1">
                    Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    className="bg-background border border-input rounded-md px-3 py-2 w-full"
                    placeholder="Enter your name" />
                </div>
                <div>
                  <label htmlFor="google-maps-link" className="block text-sm font-medium mb-1">
                    Google Maps Link
                  </label>
                  <input
                    type="text"
                    id="google-maps-link"
                    className="bg-background border border-input rounded-md px-3 py-2 w-full"
                    placeholder="Enter the Google Maps link" />
                </div>
                <Button className="w-full">Delete review</Button>
              </form>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16">
          <div className="container mx-auto max-w-5xl">
            <h2 className="text-2xl font-bold mb-4">Order History</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Google Review Removal</CardTitle>
                  <Badge variant="secondary">In Progress</Badge>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p>
                      Google Maps Link:{" "}
                      <a href="#" className="text-blue-600 underline">
                        https://goo.gl/maps/example
                      </a>
                    </p>
                    <p>Description: Negative review about our business</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Google Review Removal</CardTitle>
                  <Badge variant="secondary">In Progress</Badge>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p>
                      Google Maps Link:{" "}
                      <a href="#" className="text-blue-600 underline">
                        https://goo.gl/maps/example2
                      </a>
                    </p>
                    <p>Description: Another negative review</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Google Review Removal</CardTitle>
                  <Badge variant="secondary">Fulfilled</Badge>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p>
                      Google Maps Link:{" "}
                      <a href="#" className="text-blue-600 underline">
                        https://goo.gl/maps/example3
                      </a>
                    </p>
                    <p>Description: Negative review about our service</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-4 md:px-6">
        <div className="container mx-auto max-w-5xl">
          <p className="text-center text-sm">&copy; 2024 Your Company. All rights reserved.</p>
        </div>
      </footer>
    </div>)
  );
}
